version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Root123456
    ports:
      - "5432:5432"
    volumes:
      - my_local_data:/var/lib/postgresql/data

volumes:
  my_local_data:
